apiVersion: v1
kind: ConfigMap
metadata:
  name: anomaly-detection
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.env.config | toYaml | indent 2 }}
  {{ .Values.env.secrets | toYaml | indent 2 }}